# From fastapi package import FastAPI class
from fastapi import FastAPI 

# create an object of FastAPI class 
app = FastAPI()

# Define Route/Endpoint to connect with app and method [GET, POST]
@app.get('/') #[If any one add /- Home url to website after domain api.example.com/ .. They will call our hello function]
def helloWorld():
    print('Hello World !! First Fast API Program')
    # Return JSON object as an output
    return {"message": "Hello World ! First API Program.."}

@app.get('/about')
def about():
    print("Message ---> I am Prince Sharma")
    return {"message":"I am Prince Sharma"}

#To execute run below command 
# Navigate to main code before starting the uvicorn server
# uvicorn main:app --reload [reload - if any changes will happend, server will automatically reload the new code. no manual intervention required.]
# It will start a server and start listneing http request 
    
# http://127.0.0.1:8000/docs
## /docs provide autogenerated documentation and test for created API